AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create DynamoDB table and import data from S3'

Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table
    Default: vehicles

  S3BucketName:
    Type: String
    Description: Name of the S3 bucket containing the import file
    Default: vehicles-import-dynamodb

  S3KeyName:
    Type: String
    Description: Path to the import file in S3
    Default: five-million.csv

Resources:
  # DynamoDB Table Definition
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ImportSourceSpecification:
        S3BucketSource:
          S3Bucket: !Ref S3BucketName
        InputFormat: CSV

  # IAM Role for Import
  DynamoDBImportRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: DynamoDBImportPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                Resource: !GetAtt DynamoDBTable.Arn

Outputs:
  TableName:
    Description: Name of the created DynamoDB table
    Value: !Ref DynamoDBTable

  TableArn:
    Description: ARN of the created DynamoDB table
    Value: !GetAtt DynamoDBTable.Arn
